name: Build Next.js and Deploy to cPanel Branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js
        run: yarn build --no-lint --turbo

      - name: Prepare deploy branch
        run: |
          git config --global user.name "Hilal Ahmad"
          git config --global user.email "ihilalahmadd@gmail.com"

          # create orphan deploy branch
          git checkout --orphan deploy
          git reset

          # make a temporary folder for deployment
          mkdir deploy-temp
          cp -r .next deploy-temp/
          cp -r public deploy-temp/
          cp package.json deploy-temp/
          cp yarn.lock deploy-temp/
          cp server.js deploy-temp/

          # copy next.config.js if it exists
          if [ -f next.config.js ]; then
            cp next.config.js deploy-temp/
          fi
          if [ -f next.config.ts ]; then
            cp next.config.ts deploy-temp/
          fi

          # move into temp folder
          cd deploy-temp
          git init
          git add .
          git commit -m "Deploy production build"
          git branch -M deploy
          git remote add origin https://github.com/ihilalahmad/next-js-testing.git
          git push -f origin deploy
